# Generated by Django 3.1.2 on 2020-10-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Price',
            new_name='price',
        ),
    ]
