# Generated by Django 3.0.2 on 2020-10-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellapp.Post')),
            ],
        ),
    ]
