# Generated by Django 3.0.2 on 2020-10-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0004_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='product',
            new_name='post',
        ),
    ]
