# Generated by Django 3.0.2 on 2020-10-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0005_auto_20201024_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post',
            new_name='title',
        ),
    ]
