# Generated by Django 3.0.2 on 2020-10-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0006_auto_20201024_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='title',
            new_name='product',
        ),
    ]
