# Generated by Django 3.0.2 on 2020-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0008_auto_20201024_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='Post'),
        ),
    ]
