# Generated by Django 3.0.2 on 2020-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0009_auto_20201024_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Post'),
        ),
    ]
