# Generated by Django 3.0.2 on 2020-10-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0010_auto_20201025_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
