# Generated by Django 3.0.2 on 2020-10-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellapp', '0011_auto_20201025_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellapp.Post', verbose_name='commentpost'),
        ),
    ]
